# Remove the include below to disconnect Kitty from Omarchy's theming system.
include ~/.local/state/omarchy/current/theme/kitty.conf

# Settings below override Omarchy's defaults in /etc/xdg/kitty/kitty.conf.
# Learn more: https://sw.kovidgoyal.net/kitty/conf/

# Font
# font_family JetBrainsMono Nerd Font
# font_size 12

# Window padding
# window_padding_width 14

# Unmap a shortcut, passing it through to the terminal application
# map ctrl+insert

# Set or replace a shortcut
# map ctrl+shift+c copy_to_clipboard

# Remove all inherited shortcuts, including Kitty's built-in shortcuts
# clear_all_shortcuts yes

font_family HackGen Console NF
